### ISSUE TITLE
No description in several default components

### ISSUE THREAD

**Issue by larsviktorlarsson** [Hopsan/hopsan#1982] opened 2020-08-21 07:00 UTC
**Describe the bug**
*Description is missing in plenty of the default components.*

**To Reproduce**
*If the bug can be reproduce, please give the steps taken to reproduce the behavior:*
1. Open the component properties dialogue of e.g. Q_type_Fixed_Displacement_Motor
2. Description tab is missing
3. If "Description" button is pushed, an empty window is opened

**Expected behavior**
*All components should have descriptions, perhaps it should always be in .md format?
Since this fix will take a long time, maybe one should open a pull request which anyone interested could commit to?*

**Comment by robbr48** [comment] 2020-08-21 07:14
Duplicate of #1980. Let's continue the discussion there.

**Closed by robbr48** 2020-08-21 07:14 UTC
