### ISSUE TITLE
logonly matches all signals on port

### ISSUE THREAD

**Issue by mrejster** [Hopsan/hopsan#1976] opened 2020-08-19 10:27 UTC
**Describe the bug**
When using hopsanCLI, the logonly is crucial for reducing output file size. However, the matching of port names do not work as expected. For example, if I wish to log only the signal:
lineRCandLosses_24#P2#Flow

I end up only saving every other value on that port, i.e.,
lineRCandLosses_24#P2#Pressure
lineRCandLosses_24#P2#Temperature
etc. resulting in around 4x larger csv files than needed (=slow)

**To Reproduce**
run a model using hopsanCLI
export data to csv using the logonly-flag and a single port name

**Expected behavior**
Only the exact match should be exported

**Hopsan version (please complete the following information):**
*Version information is shown in the message widget when HopsanGUI is started*
 - OS: Windows 10
 - Version: [e.g. HopsanCore 64-bit, Version: 2.14.1
                       HopsanGUI 64-bit, Version: 2.14.1
 - Build: Official

**Additional information**
The option to also export as .h5 would be great!

**Comment by peterNordin** [comment] 2020-08-19 20:19
Currently the logonly option specifies Ports, not variables in ports so the entire port will be logged to memory and this is not easy to change. But I guess we could choose what to export in the export step, to atleast create a smaller csv file.

.h5 support is also very time consuming to implement. Since it is a function built into the GUI, we would need to create a new "result logging" library, loaded by both the cli and gui, (like hopsangenerator). This would be nice to have, but it will take to much time.

But I guess one thing that could work (and is easier to implement) is to create a "binary csv" format, that doesn't write the values as text, I think that would be more compact and likely faster to write/read.

**Comment by mrejster** [comment] 2020-08-20 05:20
Ok, understood. I can live with the slowdown for now. I found a much bigger issue with the parameter import, I'll file a new issue for that.

**Comment by robbr48** [comment] 2020-08-20 10:04
I workaround here is to use sensor components for the important variables, and log the sensor output. Signal ports only have one variable.

**Comment by peterNordin** [comment] 2020-08-23 19:42
Also noticed a potential problem, the output uses scientific notation but the default precision of 6 significant numbers.
Increasing it would make files even larger, so maybe saving data as binary could be useful.

**Comment by mrejster** [comment] 2020-08-24 06:55
Ok, yes that could be an issue.

A possible(?) workaround for h5 export: maybe hopsan CLI can be modified to accept a script file in the the call. Then the regular sapl h5-functionality could be used. or maybe HCOM is tightly connected to hopsan GUI...

**Comment by robbr48** [comment] 2020-08-24 07:03
@mrejster HCOM is GUI only. Of course we could call HopsanGUI with a HCOM script, we want HopsanCLI to work as a stand-alone executable independent of the GUI.

@peterNordin Is it really that time consuming to add HDF5 export to CLI? The actual export code is only ~140 lines of code. Of course we cannot use the GUI log data handler. It would be a two-step process; first move the export code to a new HopsanGenerator utility, and then call this utility from CLI.

**Comment by peterNordin** [comment] 2020-08-24 18:19
Well maybe its not so time consuming, I was thinking of moving a lot of functionality to such a library. But it its only the data export it might be doable. Maybe for the next version.

**Comment by peterNordin** [comment] 2020-09-03 12:44
So the only remaining issue here is if precision for csv data should be increased, (or configurable), could maybe be postponed for later since hdf5 support will be added.

**Comment by peterNordin** [comment] 2020-09-09 14:49
A second issue is that the new logonly match for variables probably does not work for hdf5 output, need to verify or fix that before closing this

**Comment by mrejster** [comment] 2020-09-17 09:24
Not sure if this is known already, but another issue with the export is that all subsystem Time-vectors are exported as well, even if no other signal is exported from respective subsystem.  for our type of models, with lots of small subsystems with identical time vectors, this results in lots of extra data, around 60 extra variables for the model I'm working on right now. So the output csv is around 90% waste ;)

**Comment by peterNordin** [comment] 2020-09-17 16:57
Ahh yes, I knew about that, but I did not consider a use case with so many subsystems. I will try to fix it. Time variables are currently handled separately from the log variables.

So essentially you would like to: Only include time variables for systems where at least one log variable was enabled. 
That makes sense I think.

I have to think about what happens for system ports though, I don't remember if they are logged in the parent system or by the "self system".

**Comment by peterNordin** [comment] 2020-09-24 16:56
An update on this issue, I am merging the code for CSV and hdf5 output so that they will behave the same with regards to logonly and subsystem time vectors. But I ran into some strange problems with the new hdf5 exporter on the unittestmodel that I also need to resolve.

**Comment by peterNordin** [comment] 2020-09-25 16:44
@robbr48 and @mrejster I ran in to a tricky problem when running my new code on the unittestmodel. The problem is that it contains components named "Time" and when the Time vector of the subsystem in particular is being exported the HDF5 dataset created will have a name collision and the export is aborted.  I have the following ideas for "solving this", what are your thoughts.

1. If a dataset fails, just ignore it and do not export that data, but continue with the rest of the variables. <- This is the solution I have currently implemented, and its a sane fallback solution.
2. Reserve the name "Time" and "time" inside HopsanCore so that you can not create components/ports and such with this name. This avoids collision, but existing models will break.
3. Reserve only lower-case "time" and change the name of the time vector (both in CLI and GUI) to lower-case "time", instead of "Time". Then you can still have components named Time, (the default name for the Time component in the default library). This leads to fewer broken models.
4. Change the name of datasets that can not be created in the HDF5 file to avoid collision. I do not like this solution, since then sometimes it will be called "Time", and other times "time" 

I prefer option 2 or 3.
Maybe option three seems best, but then all occurrences of Time should be changed to time. (When we are talking about the time vector). And since all other variable names start with a upper-case letter, it may look out of place.
So maybe we have to go with option 2, at least an Error message about fails connections is shown, so the user should be able to fix the model.

**Comment by robbr48** [comment] 2020-10-07 11:12
"Time" is a weird name for the component anyway. It is unclear to the user whether it is simulation time, wall time, system time or something else. I suggest we change the component default name to "Simulation Time" (but keeping the type name), and then reserve the name "Time". We can solve the backwards compatibility by automatically renaming any component named "Time" in the existing ```verifyHmfComponentCompatibility()``` function.

**Comment by peterNordin** [comment] 2020-11-02 19:11
I think the main issues are solved by the merged PRs

**Closed by peterNordin** 2020-11-02 19:11 UTC
Labels: CLI, enhancement
