### ISSUE TITLE
Hopsan chrashes when a connected input variable port is disabled

### ISSUE THREAD

**Issue by samuelkarnell** [Hopsan/hopsan#2094] opened 2021-07-07 07:09 UTC
**Describe the bug**
Hopsan stops to respond if the port is disabled for an input variable that already is connected to a signal.

**To Reproduce**
1. Add a Constant and a C_type_Pressure_Source
2. Connect the constant to the p-port on the pressure source
3. Open the component properties for the C_type_Pressure_Source and uncheck the port-box for the input variable
4. Hopsan will no longer respond

**Expected behavior**
The connection between the components was expected to be removed.

**Hopsan version (please complete the following information):**
 - OS: Windows 10
 - Version:  HopsanCore 64-bit, Version: 2.9.0.20210510.1936
                       HopsanGUI 64-bit, Version: 2.9.0.20210510.1936
                       Build: **official** build downloaded from the web page.

**Comment by robbr48** [comment] 2021-07-08 08:55
Confirmed. I see three possible solutions:
1. Disable the checkbox for all connected ports
2. Remove the connector if the checkbox is unchecked
3. Keep a dangling connector if the checkbox is unchecked

I think I prefer solution 1 or 3. Removing a connector can be confusing if the user did not expect it.

**Comment by robbr48** [comment] 2021-07-09 11:46
After looking deeper into this I found out that the code already attempts to remove the connector. The problem is that the model is locked while the dialog is open, so removing the connector is not allowed. Unfortunately the removal is implemented as a while-loop, so it will continue trying to remove the connector forever. 

It can probably be fixed by adding a "force removal" argument, but that may cause other problems if two dialogs are open. The model is locked for a reason. I still vote for solution 1 in the list above.

**Comment by samuelkarnell** [comment] 2021-07-09 11:59
I have no strong feelings in this matter, but solution 1 sounds reasonable. I expected the connector to be removed when I unchecked the box, but I can see that there is a risk with allowing this as well.

**Comment by peterNordin** [comment] 2021-07-09 15:24
Yes option 1, seems the most reasonable (and easy to implement)

**Comment by peterNordin** [comment] 2021-07-09 15:38
Looked at the code, and the reason for the freeze is that the current code calls `Port::disconnectAndRemoveAllConnectedConnectors()` but gets stuck in the while (there are connected connectors) loop.
The actual "disconnect and delete" call is ignored, since the model is in a locked state, since the properties dialog is open. 
Possibly similar bugs could be triggered elsewhere, but I think it would be enough to prevent this from happening in this particular case (by implementing option1)

**Comment by peterNordin** [comment] 2021-07-09 17:22
Aha, Robert had already found this, I did not read the thread properly, I also found that the same bug can be triggered from inside the move ports dialog. I have not coded in a while but I would like to try and fix this, can I reassign it to me @robbr48 ?

**Closed** 2021-09-06 20:09 UTC
Labels: bug, GUI:Modeling
